//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace BandoApplication
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbBarang> dbBarangs
        {
            get
            {
                if ((_dbBarangs == null))
                {
                    _dbBarangs = base.CreateObjectSet<dbBarang>("dbBarangs");
                }
                return _dbBarangs;
            }
        }
        private ObjectSet<dbBarang> _dbBarangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbPelanggan> dbPelanggans
        {
            get
            {
                if ((_dbPelanggans == null))
                {
                    _dbPelanggans = base.CreateObjectSet<dbPelanggan>("dbPelanggans");
                }
                return _dbPelanggans;
            }
        }
        private ObjectSet<dbPelanggan> _dbPelanggans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbPemesanan> dbPemesanans
        {
            get
            {
                if ((_dbPemesanans == null))
                {
                    _dbPemesanans = base.CreateObjectSet<dbPemesanan>("dbPemesanans");
                }
                return _dbPemesanans;
            }
        }
        private ObjectSet<dbPemesanan> _dbPemesanans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbUser> dbUsers
        {
            get
            {
                if ((_dbUsers == null))
                {
                    _dbUsers = base.CreateObjectSet<dbUser>("dbUsers");
                }
                return _dbUsers;
            }
        }
        private ObjectSet<dbUser> _dbUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbSuratPerintahKerja> dbSuratPerintahKerjas
        {
            get
            {
                if ((_dbSuratPerintahKerjas == null))
                {
                    _dbSuratPerintahKerjas = base.CreateObjectSet<dbSuratPerintahKerja>("dbSuratPerintahKerjas");
                }
                return _dbSuratPerintahKerjas;
            }
        }
        private ObjectSet<dbSuratPerintahKerja> _dbSuratPerintahKerjas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbSuratPengirimanBarang> dbSuratPengirimanBarangs
        {
            get
            {
                if ((_dbSuratPengirimanBarangs == null))
                {
                    _dbSuratPengirimanBarangs = base.CreateObjectSet<dbSuratPengirimanBarang>("dbSuratPengirimanBarangs");
                }
                return _dbSuratPengirimanBarangs;
            }
        }
        private ObjectSet<dbSuratPengirimanBarang> _dbSuratPengirimanBarangs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbSuratJalan> dbSuratJalans
        {
            get
            {
                if ((_dbSuratJalans == null))
                {
                    _dbSuratJalans = base.CreateObjectSet<dbSuratJalan>("dbSuratJalans");
                }
                return _dbSuratJalans;
            }
        }
        private ObjectSet<dbSuratJalan> _dbSuratJalans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dbFormRealisasiPengirimanHarian> dbFormRealisasiPengirimanHarians
        {
            get
            {
                if ((_dbFormRealisasiPengirimanHarians == null))
                {
                    _dbFormRealisasiPengirimanHarians = base.CreateObjectSet<dbFormRealisasiPengirimanHarian>("dbFormRealisasiPengirimanHarians");
                }
                return _dbFormRealisasiPengirimanHarians;
            }
        }
        private ObjectSet<dbFormRealisasiPengirimanHarian> _dbFormRealisasiPengirimanHarians;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbBarangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbBarangs(dbBarang dbBarang)
        {
            base.AddObject("dbBarangs", dbBarang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbPelanggans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbPelanggans(dbPelanggan dbPelanggan)
        {
            base.AddObject("dbPelanggans", dbPelanggan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbPemesanans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbPemesanans(dbPemesanan dbPemesanan)
        {
            base.AddObject("dbPemesanans", dbPemesanan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbUsers(dbUser dbUser)
        {
            base.AddObject("dbUsers", dbUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbSuratPerintahKerjas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbSuratPerintahKerjas(dbSuratPerintahKerja dbSuratPerintahKerja)
        {
            base.AddObject("dbSuratPerintahKerjas", dbSuratPerintahKerja);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbSuratPengirimanBarangs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbSuratPengirimanBarangs(dbSuratPengirimanBarang dbSuratPengirimanBarang)
        {
            base.AddObject("dbSuratPengirimanBarangs", dbSuratPengirimanBarang);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbSuratJalans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbSuratJalans(dbSuratJalan dbSuratJalan)
        {
            base.AddObject("dbSuratJalans", dbSuratJalan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dbFormRealisasiPengirimanHarians EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodbFormRealisasiPengirimanHarians(dbFormRealisasiPengirimanHarian dbFormRealisasiPengirimanHarian)
        {
            base.AddObject("dbFormRealisasiPengirimanHarians", dbFormRealisasiPengirimanHarian);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="dbBarang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbBarang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbBarang object.
        /// </summary>
        /// <param name="idBarang">Initial value of the IdBarang property.</param>
        public static dbBarang CreatedbBarang(global::System.String idBarang)
        {
            dbBarang dbBarang = new dbBarang();
            dbBarang.IdBarang = idBarang;
            return dbBarang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdBarang
        {
            get
            {
                return _IdBarang;
            }
            set
            {
                if (_IdBarang != value)
                {
                    OnIdBarangChanging(value);
                    ReportPropertyChanging("IdBarang");
                    _IdBarang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdBarang");
                    OnIdBarangChanged();
                }
            }
        }
        private global::System.String _IdBarang;
        partial void OnIdBarangChanging(global::System.String value);
        partial void OnIdBarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NamaBarang
        {
            get
            {
                return _NamaBarang;
            }
            set
            {
                OnNamaBarangChanging(value);
                ReportPropertyChanging("NamaBarang");
                _NamaBarang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NamaBarang");
                OnNamaBarangChanged();
            }
        }
        private global::System.String _NamaBarang;
        partial void OnNamaBarangChanging(global::System.String value);
        partial void OnNamaBarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JenisBarang
        {
            get
            {
                return _JenisBarang;
            }
            set
            {
                OnJenisBarangChanging(value);
                ReportPropertyChanging("JenisBarang");
                _JenisBarang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JenisBarang");
                OnJenisBarangChanged();
            }
        }
        private global::System.String _JenisBarang;
        partial void OnJenisBarangChanging(global::System.String value);
        partial void OnJenisBarangChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="dbFormRealisasiPengirimanHarian")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbFormRealisasiPengirimanHarian : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbFormRealisasiPengirimanHarian object.
        /// </summary>
        /// <param name="idFormRealisasiPengirimanHarian">Initial value of the IdFormRealisasiPengirimanHarian property.</param>
        public static dbFormRealisasiPengirimanHarian CreatedbFormRealisasiPengirimanHarian(global::System.String idFormRealisasiPengirimanHarian)
        {
            dbFormRealisasiPengirimanHarian dbFormRealisasiPengirimanHarian = new dbFormRealisasiPengirimanHarian();
            dbFormRealisasiPengirimanHarian.IdFormRealisasiPengirimanHarian = idFormRealisasiPengirimanHarian;
            return dbFormRealisasiPengirimanHarian;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdFormRealisasiPengirimanHarian
        {
            get
            {
                return _IdFormRealisasiPengirimanHarian;
            }
            set
            {
                if (_IdFormRealisasiPengirimanHarian != value)
                {
                    OnIdFormRealisasiPengirimanHarianChanging(value);
                    ReportPropertyChanging("IdFormRealisasiPengirimanHarian");
                    _IdFormRealisasiPengirimanHarian = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdFormRealisasiPengirimanHarian");
                    OnIdFormRealisasiPengirimanHarianChanged();
                }
            }
        }
        private global::System.String _IdFormRealisasiPengirimanHarian;
        partial void OnIdFormRealisasiPengirimanHarianChanging(global::System.String value);
        partial void OnIdFormRealisasiPengirimanHarianChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdSuratJalan
        {
            get
            {
                return _IdSuratJalan;
            }
            set
            {
                OnIdSuratJalanChanging(value);
                ReportPropertyChanging("IdSuratJalan");
                _IdSuratJalan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdSuratJalan");
                OnIdSuratJalanChanged();
            }
        }
        private global::System.String _IdSuratJalan;
        partial void OnIdSuratJalanChanging(global::System.String value);
        partial void OnIdSuratJalanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Komentar
        {
            get
            {
                return _Komentar;
            }
            set
            {
                OnKomentarChanging(value);
                ReportPropertyChanging("Komentar");
                _Komentar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Komentar");
                OnKomentarChanged();
            }
        }
        private global::System.String _Komentar;
        partial void OnKomentarChanging(global::System.String value);
        partial void OnKomentarChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="dbPelanggan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbPelanggan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbPelanggan object.
        /// </summary>
        /// <param name="idPelanggan">Initial value of the IdPelanggan property.</param>
        public static dbPelanggan CreatedbPelanggan(global::System.String idPelanggan)
        {
            dbPelanggan dbPelanggan = new dbPelanggan();
            dbPelanggan.IdPelanggan = idPelanggan;
            return dbPelanggan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdPelanggan
        {
            get
            {
                return _IdPelanggan;
            }
            set
            {
                if (_IdPelanggan != value)
                {
                    OnIdPelangganChanging(value);
                    ReportPropertyChanging("IdPelanggan");
                    _IdPelanggan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdPelanggan");
                    OnIdPelangganChanged();
                }
            }
        }
        private global::System.String _IdPelanggan;
        partial void OnIdPelangganChanging(global::System.String value);
        partial void OnIdPelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nama
        {
            get
            {
                return _Nama;
            }
            set
            {
                OnNamaChanging(value);
                ReportPropertyChanging("Nama");
                _Nama = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nama");
                OnNamaChanged();
            }
        }
        private global::System.String _Nama;
        partial void OnNamaChanging(global::System.String value);
        partial void OnNamaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Alamat
        {
            get
            {
                return _Alamat;
            }
            set
            {
                OnAlamatChanging(value);
                ReportPropertyChanging("Alamat");
                _Alamat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Alamat");
                OnAlamatChanged();
            }
        }
        private global::System.String _Alamat;
        partial void OnAlamatChanging(global::System.String value);
        partial void OnAlamatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telepon
        {
            get
            {
                return _Telepon;
            }
            set
            {
                OnTeleponChanging(value);
                ReportPropertyChanging("Telepon");
                _Telepon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telepon");
                OnTeleponChanged();
            }
        }
        private global::System.String _Telepon;
        partial void OnTeleponChanging(global::System.String value);
        partial void OnTeleponChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="dbPemesanan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbPemesanan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbPemesanan object.
        /// </summary>
        /// <param name="idPemesanan">Initial value of the IdPemesanan property.</param>
        public static dbPemesanan CreatedbPemesanan(global::System.String idPemesanan)
        {
            dbPemesanan dbPemesanan = new dbPemesanan();
            dbPemesanan.IdPemesanan = idPemesanan;
            return dbPemesanan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdPemesanan
        {
            get
            {
                return _IdPemesanan;
            }
            set
            {
                if (_IdPemesanan != value)
                {
                    OnIdPemesananChanging(value);
                    ReportPropertyChanging("IdPemesanan");
                    _IdPemesanan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdPemesanan");
                    OnIdPemesananChanged();
                }
            }
        }
        private global::System.String _IdPemesanan;
        partial void OnIdPemesananChanging(global::System.String value);
        partial void OnIdPemesananChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdPelanggan
        {
            get
            {
                return _IdPelanggan;
            }
            set
            {
                OnIdPelangganChanging(value);
                ReportPropertyChanging("IdPelanggan");
                _IdPelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdPelanggan");
                OnIdPelangganChanged();
            }
        }
        private global::System.String _IdPelanggan;
        partial void OnIdPelangganChanging(global::System.String value);
        partial void OnIdPelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdBarang
        {
            get
            {
                return _IdBarang;
            }
            set
            {
                OnIdBarangChanging(value);
                ReportPropertyChanging("IdBarang");
                _IdBarang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdBarang");
                OnIdBarangChanged();
            }
        }
        private global::System.String _IdBarang;
        partial void OnIdBarangChanging(global::System.String value);
        partial void OnIdBarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NamaBarang
        {
            get
            {
                return _NamaBarang;
            }
            set
            {
                OnNamaBarangChanging(value);
                ReportPropertyChanging("NamaBarang");
                _NamaBarang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NamaBarang");
                OnNamaBarangChanged();
            }
        }
        private global::System.String _NamaBarang;
        partial void OnNamaBarangChanging(global::System.String value);
        partial void OnNamaBarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JenisBarang
        {
            get
            {
                return _JenisBarang;
            }
            set
            {
                OnJenisBarangChanging(value);
                ReportPropertyChanging("JenisBarang");
                _JenisBarang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JenisBarang");
                OnJenisBarangChanged();
            }
        }
        private global::System.String _JenisBarang;
        partial void OnJenisBarangChanging(global::System.String value);
        partial void OnJenisBarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="dbSuratJalan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbSuratJalan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbSuratJalan object.
        /// </summary>
        /// <param name="idSuratJalan">Initial value of the IdSuratJalan property.</param>
        public static dbSuratJalan CreatedbSuratJalan(global::System.String idSuratJalan)
        {
            dbSuratJalan dbSuratJalan = new dbSuratJalan();
            dbSuratJalan.IdSuratJalan = idSuratJalan;
            return dbSuratJalan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdSuratJalan
        {
            get
            {
                return _IdSuratJalan;
            }
            set
            {
                if (_IdSuratJalan != value)
                {
                    OnIdSuratJalanChanging(value);
                    ReportPropertyChanging("IdSuratJalan");
                    _IdSuratJalan = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdSuratJalan");
                    OnIdSuratJalanChanged();
                }
            }
        }
        private global::System.String _IdSuratJalan;
        partial void OnIdSuratJalanChanging(global::System.String value);
        partial void OnIdSuratJalanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdSuratPengirimanBarang
        {
            get
            {
                return _IdSuratPengirimanBarang;
            }
            set
            {
                OnIdSuratPengirimanBarangChanging(value);
                ReportPropertyChanging("IdSuratPengirimanBarang");
                _IdSuratPengirimanBarang = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdSuratPengirimanBarang");
                OnIdSuratPengirimanBarangChanged();
            }
        }
        private global::System.String _IdSuratPengirimanBarang;
        partial void OnIdSuratPengirimanBarangChanging(global::System.String value);
        partial void OnIdSuratPengirimanBarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NamaSupir
        {
            get
            {
                return _NamaSupir;
            }
            set
            {
                OnNamaSupirChanging(value);
                ReportPropertyChanging("NamaSupir");
                _NamaSupir = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NamaSupir");
                OnNamaSupirChanged();
            }
        }
        private global::System.String _NamaSupir;
        partial void OnNamaSupirChanging(global::System.String value);
        partial void OnNamaSupirChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RutePengiriman
        {
            get
            {
                return _RutePengiriman;
            }
            set
            {
                OnRutePengirimanChanging(value);
                ReportPropertyChanging("RutePengiriman");
                _RutePengiriman = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RutePengiriman");
                OnRutePengirimanChanged();
            }
        }
        private global::System.String _RutePengiriman;
        partial void OnRutePengirimanChanging(global::System.String value);
        partial void OnRutePengirimanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JarakTotal
        {
            get
            {
                return _JarakTotal;
            }
            set
            {
                OnJarakTotalChanging(value);
                ReportPropertyChanging("JarakTotal");
                _JarakTotal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JarakTotal");
                OnJarakTotalChanged();
            }
        }
        private global::System.String _JarakTotal;
        partial void OnJarakTotalChanging(global::System.String value);
        partial void OnJarakTotalChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="dbSuratPengirimanBarang")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbSuratPengirimanBarang : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbSuratPengirimanBarang object.
        /// </summary>
        /// <param name="idSuratPengirimanBarang">Initial value of the IdSuratPengirimanBarang property.</param>
        public static dbSuratPengirimanBarang CreatedbSuratPengirimanBarang(global::System.String idSuratPengirimanBarang)
        {
            dbSuratPengirimanBarang dbSuratPengirimanBarang = new dbSuratPengirimanBarang();
            dbSuratPengirimanBarang.IdSuratPengirimanBarang = idSuratPengirimanBarang;
            return dbSuratPengirimanBarang;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdSuratPengirimanBarang
        {
            get
            {
                return _IdSuratPengirimanBarang;
            }
            set
            {
                if (_IdSuratPengirimanBarang != value)
                {
                    OnIdSuratPengirimanBarangChanging(value);
                    ReportPropertyChanging("IdSuratPengirimanBarang");
                    _IdSuratPengirimanBarang = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdSuratPengirimanBarang");
                    OnIdSuratPengirimanBarangChanged();
                }
            }
        }
        private global::System.String _IdSuratPengirimanBarang;
        partial void OnIdSuratPengirimanBarangChanging(global::System.String value);
        partial void OnIdSuratPengirimanBarangChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdSuratPerintahKerja
        {
            get
            {
                return _IdSuratPerintahKerja;
            }
            set
            {
                OnIdSuratPerintahKerjaChanging(value);
                ReportPropertyChanging("IdSuratPerintahKerja");
                _IdSuratPerintahKerja = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdSuratPerintahKerja");
                OnIdSuratPerintahKerjaChanged();
            }
        }
        private global::System.String _IdSuratPerintahKerja;
        partial void OnIdSuratPerintahKerjaChanging(global::System.String value);
        partial void OnIdSuratPerintahKerjaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NamaPelanggan
        {
            get
            {
                return _NamaPelanggan;
            }
            set
            {
                OnNamaPelangganChanging(value);
                ReportPropertyChanging("NamaPelanggan");
                _NamaPelanggan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NamaPelanggan");
                OnNamaPelangganChanged();
            }
        }
        private global::System.String _NamaPelanggan;
        partial void OnNamaPelangganChanging(global::System.String value);
        partial void OnNamaPelangganChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tujuan
        {
            get
            {
                return _Tujuan;
            }
            set
            {
                OnTujuanChanging(value);
                ReportPropertyChanging("Tujuan");
                _Tujuan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tujuan");
                OnTujuanChanged();
            }
        }
        private global::System.String _Tujuan;
        partial void OnTujuanChanging(global::System.String value);
        partial void OnTujuanChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="dbSuratPerintahKerja")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbSuratPerintahKerja : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbSuratPerintahKerja object.
        /// </summary>
        /// <param name="idSuratPerintahKerja">Initial value of the IdSuratPerintahKerja property.</param>
        public static dbSuratPerintahKerja CreatedbSuratPerintahKerja(global::System.String idSuratPerintahKerja)
        {
            dbSuratPerintahKerja dbSuratPerintahKerja = new dbSuratPerintahKerja();
            dbSuratPerintahKerja.IdSuratPerintahKerja = idSuratPerintahKerja;
            return dbSuratPerintahKerja;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdSuratPerintahKerja
        {
            get
            {
                return _IdSuratPerintahKerja;
            }
            set
            {
                if (_IdSuratPerintahKerja != value)
                {
                    OnIdSuratPerintahKerjaChanging(value);
                    ReportPropertyChanging("IdSuratPerintahKerja");
                    _IdSuratPerintahKerja = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdSuratPerintahKerja");
                    OnIdSuratPerintahKerjaChanged();
                }
            }
        }
        private global::System.String _IdSuratPerintahKerja;
        partial void OnIdSuratPerintahKerjaChanging(global::System.String value);
        partial void OnIdSuratPerintahKerjaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IdPemesanan
        {
            get
            {
                return _IdPemesanan;
            }
            set
            {
                OnIdPemesananChanging(value);
                ReportPropertyChanging("IdPemesanan");
                _IdPemesanan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IdPemesanan");
                OnIdPemesananChanged();
            }
        }
        private global::System.String _IdPemesanan;
        partial void OnIdPemesananChanging(global::System.String value);
        partial void OnIdPemesananChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tanggal
        {
            get
            {
                return _Tanggal;
            }
            set
            {
                OnTanggalChanging(value);
                ReportPropertyChanging("Tanggal");
                _Tanggal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tanggal");
                OnTanggalChanged();
            }
        }
        private global::System.String _Tanggal;
        partial void OnTanggalChanging(global::System.String value);
        partial void OnTanggalChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="dbUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dbUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dbUser object.
        /// </summary>
        /// <param name="idUser">Initial value of the IdUser property.</param>
        public static dbUser CreatedbUser(global::System.String idUser)
        {
            dbUser dbUser = new dbUser();
            dbUser.IdUser = idUser;
            return dbUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IdUser
        {
            get
            {
                return _IdUser;
            }
            set
            {
                if (_IdUser != value)
                {
                    OnIdUserChanging(value);
                    ReportPropertyChanging("IdUser");
                    _IdUser = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IdUser");
                    OnIdUserChanged();
                }
            }
        }
        private global::System.String _IdUser;
        partial void OnIdUserChanging(global::System.String value);
        partial void OnIdUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NamaUser
        {
            get
            {
                return _NamaUser;
            }
            set
            {
                OnNamaUserChanging(value);
                ReportPropertyChanging("NamaUser");
                _NamaUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NamaUser");
                OnNamaUserChanged();
            }
        }
        private global::System.String _NamaUser;
        partial void OnNamaUserChanging(global::System.String value);
        partial void OnNamaUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AlamatUser
        {
            get
            {
                return _AlamatUser;
            }
            set
            {
                OnAlamatUserChanging(value);
                ReportPropertyChanging("AlamatUser");
                _AlamatUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AlamatUser");
                OnAlamatUserChanged();
            }
        }
        private global::System.String _AlamatUser;
        partial void OnAlamatUserChanging(global::System.String value);
        partial void OnAlamatUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telepon
        {
            get
            {
                return _Telepon;
            }
            set
            {
                OnTeleponChanging(value);
                ReportPropertyChanging("Telepon");
                _Telepon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telepon");
                OnTeleponChanged();
            }
        }
        private global::System.String _Telepon;
        partial void OnTeleponChanging(global::System.String value);
        partial void OnTeleponChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Jabatan
        {
            get
            {
                return _Jabatan;
            }
            set
            {
                OnJabatanChanging(value);
                ReportPropertyChanging("Jabatan");
                _Jabatan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Jabatan");
                OnJabatanChanged();
            }
        }
        private global::System.String _Jabatan;
        partial void OnJabatanChanging(global::System.String value);
        partial void OnJabatanChanged();

        #endregion
    
    }

    #endregion
    
}
